### ISSUE TITLE
Is it possible to synchronize with Adguard running on a port other than 80?

### ISSUE THREAD

**Issue by alexsahka** [atoy3731/adguard-sync#12]
Im running primary Adguard on the OPNsense and port 80 is used.
And primary Adguard admin GUI running on port 3000 

-e "ADGUARD_PRIMARY=http://192.168.1.2:3000" \

Im getting an error:

Running Adguard Sync for 'http://192.168.1.2:3000' => 'http://192.168.1.5'.
  - Syncing custom rules
ERROR: Not able to reach AdGuard. Is it running?

**Comment by atoy3731** [comment]
The GUI port differs from the API port. If you want to use a different port, you'd need to modify your AdguardHome deployment to forward port 80 from the container to a different port, like so (using docker-compose as an example):

```yaml
version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    volumes:
    - /opt/adguard/work:/opt/adguardhome/work
    - /opt/adguard/conf:/opt/adguardhome/conf
    - /opt/adguard/certs:/opt/adguardhome/certs
    restart: always
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/udp"
    - "3001:80/tcp" # This is forwarding port 80 to 3001
    - "443:443/tcp"
    - "853:853/tcp"
    - "3000:3000/tcp"
```

Then you can configure your environment variable to point to 3001, like so: `ADGUARD_PRIMARY=http://192.168.1.2:3001`
