### ISSUE TITLE
The process seems to get stuck upon start of the container and doesn't sync any changes

### ISSUE THREAD

**Issue by digitalapnea** [atoy3731/adguard-sync#9]
Thanks for creating this software, it will be very handy for me when I get it up and running. I'm having some issues and wondered if you could help?

Here is my environment:

**Primary AdGuard host**
- Host IP: 192.168.88.174
- Docker container image for AdGuard: adguard/adguardhome:latest
- AdGuard container name: adguard
- AdGuard container exposed ports: 53:53/tcp, 53:53/udp, 853:853/tcp, 3000:3000/tcp
- Also running on this host is the Docker container image for **adguard-sync**: atoy3731/adguard-sync:latest

**Secondary AdGuard host**
- Host IP: 192.168.88.35
- Docker container image for AdGuard: adguard/adguardhome:latest
- AdGuard container name: adguard
- AdGuard container exposed ports: 53:53/tcp, 53:53/udp, 853:853/tcp, 3000:3000/tcp

**adguard-sync docker-compose.yml file contents**
```
version: "3.3"
services:
  agsync:
    image: atoy3731/adguard-sync:latest
    container_name: agsync
    hostname: agsync
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - ADGUARD_PRIMARY=http://192.168.88.174:3000
      - ADGUARD_SECONDARY=http://192.168.88.35:3000
      - ADGUARD_USER=admin
      - ADGUARD_PASS=********************************
      - REFRESH_INTERVAL_SECS=10

```
**Issue**
When I do a **docker-compose up -d** on the adguard-sync folder, it gets created and starts running. However when I tail the logs with **docker logs -tf adguard-sync** it just has a single entry as follows: 
2021-12-21T23:04:15.314397989Z Running Adguard Sync for 'http://192.168.88.174:3000' => 'http://192.168.88.35:3000'..

No further entries ever appear, and when I make changes to the configuration of my primary AdGuard container, they never get synchronised to the secondary one. Any ideas what might be going wrong in my setup?
